# conda-env.yml
# Configuration file for creating a Conda Environment with dependencies needed for RAPIDpy.
# Create the environment by running the following command (after installing Miniconda):
# os: linux
#   $ conda env create -f  conda-env.yml

name: rapid
channels:
- conda-forge
- defaults
dependencies:
- future
- gdal
- netcdf4
- numpy
- pandas
- requests
- pyproj
- python-dateutil
- rtree
- shapely
- scipy
